GH-179 : Implement nonce verification for Ajax calls
rtCamp/transcoder pull request #285
Opened 2024-02-21 10:51 UTC by SohamPatel46

## Description

- This PR adds WordPress Nonce fields to forms and check_ajax_referer for AJAX callbacks to ensure the security of requests. 

## Fixes/Covers
- https://github.com/rtCamp/labs/issues/179

2024-02-21 23:20 UTC, gagan0123 commented
@SohamPatel46

Can you please check why "End-to-End Tests / Playwright Tests (pull_request) " is failing and fix that before the PR is merged?

2024-02-21 23:32 UTC, gagan0123 requested changes

2024-02-21 23:32 UTC, gagan0123 commented on admin/js/rt-transcoder-admin.js
> +							security: rt_transcoder_script.security_nonce
Please use prefix for any parameter that is passed on in GET or POST requests exception being the ones that are already defined in WordPress.

In this case, we're passing `security` as a POST parameter without our prefix.

2024-02-21 23:32 UTC, gagan0123 commented on admin/rt-transcoder-admin.php
> +			'security_nonce'       => esc_js( wp_create_nonce( 'check-transcoder-ajax-nonce' ) ),
`check-transcoder-ajax-nonce`
When creating a nonce, always prefix the action. Also ensure that the action is self-descriptive, as to where it will be used.

2024-02-21 23:32 UTC, gagan0123 commented on package-lock.json
This file was not included in any of the previous commits, why add it now?

2024-02-21 23:32 UTC, gagan0123 commented on admin/js/build/rt-transcoder-block-editor-support.build.js
Always commit build files in a separate commit; otherwise it becomes difficult to revert if needed, causing conflicts. Please take care of it from next time.

2024-02-22 07:09 UTC, gagan0123 requested changes

2024-02-22 07:09 UTC, gagan0123 commented on admin/js/rt-transcoder-admin.js
> +							rt_transcoder_security: rt_transcoder_script.security_nonce
- [ ] Instead of `rt_transcoder_security` can we name it `rt_transcoder_nonce` for more clarity?

2024-02-22 07:11 UTC, gagan0123 requested changes

2024-02-22 07:11 UTC, gagan0123 commented on admin/js/build/rt-transcoder-block-editor-support.build.js
You did not edit the source for this file, why pushing the build file for this?

2024-02-22 07:39 UTC, SohamPatel46 commented on admin/js/build/rt-transcoder-block-editor-support.build.js
There is some issue while building files. This file got affected while runing `npm run build` command. Reverting this file 👍

2024-02-22 07:55 UTC, SohamPatel46 commented
@gagan0123 Implemented specific nonce creation for every action. 

Still there are 2 ajax callbacks whose action can't be located in the codebase - https://github.com/rtCamp/transcoder/blob/master/admin/rt-transcoder-handler.php#L183-#L184
Should we skip this or is there any way to tackle it ?

2024-02-22 15:01 UTC, gagan0123 commented
> @gagan0123 Implemented specific nonce creation for every action.
> 
> Still there are 2 ajax callbacks whose action can't be located in the codebase - https://github.com/rtCamp/transcoder/blob/master/admin/rt-transcoder-handler.php#L183-#L184 Should we skip this or is there any way to tackle it ?

@SohamPatel46 You can remove that part of code, I've verified that it was used before, but later the functionality was removed without removing the WP AJAX endpoints.
So remove both ensuring:

- [ ] The `add_action` for the two WP AJAX requests are removed as well
- [ ] The callback functions are also removed, after verifying they are not used anywhere else in the code

2024-02-23 05:12 UTC, SohamPatel46 commented
@gagan0123 Removed unused AJAX actions and callback. Can you re-review it ?

2024-02-23 13:20 UTC, gagan0123 commented
Thanks @SohamPatel46 for the PR 👍 

@pavanpatil1 can you please test this branch to ensure the functionality is not impacted. Code looks good to me.

2024-02-26 07:23 UTC, pavanpatil1 approved these changes

2024-02-26 09:37 UTC, gagan0123 approved these changes

2024-02-26 09:55 UTC, merged